#!/usr/bin/env bash

# To implement this command, edit the "Command implementation" section below. 

# Usage
# -----

# Comments prefixed with `#/` are managed by stubbs.
# The `command` and `usage` comments describe the command
# and show its options.
# 
#/ command: docker-machine-node-executor:dispatch: "dispatch the command"
#/ usage: rerun docker-machine-node-executor:dispatch  --command <>  --machine <>  --machine-storage-path <${MACHINE_STORAGE_PATH:-}> 

# Load common functions
# ---------------------

# Load the function library for this module.
# This loads rerun functions, too.
. $RERUN_MODULE_DIR/lib/functions.sh dispatch || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------

# This script is designed to _fail-fast_.

# Trap errors and exit. The call to `rerun_die` will print the
# the error message and exit with the error command exit status. 

trap 'rerun_die $? "*** command failed: docker-machine-node-executor:dispatch. ***"' ERR

# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
# so a pipeline return status is the value of the last 
# (rightmost) command to exit with non-zero status.
#
# [set]: http://ss64.com/bash/set.html
# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html

set -o nounset -o pipefail

# Command variables
# -----------------

# This command script can access the following variables
# declared by `rerun` or by the option parser function.

#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: COMMAND MACHINE MACHINE_STORAGE_PATH

# The `rerun_options_parse` function processes the command line
# arguments. Each accepted command line flag results in setting 
# one the corresponding option variables.


rerun_options_parse "$@"


# Command implementation
# ----------------------

export PATH=$PATH:/usr/bin

# Set the docker command
: ${DOCKER_COMMAND:=docker-machine}

set -- $COMMAND

case "$1" in
	docker-machine)
    	if [[ "$2" =~ (config|env|inspect|ip|kill|restart|rm|start|stop|upgrade|url) ]]
    	then
	  	 	rerun_log info "executing: ${DOCKER_COMMAND} $2 $MACHINE"
    		${DOCKER_COMMAND} $2 $MACHINE
    	else
    		rerun_die 3 "command no supported: $1 $2"
    	fi
    	;;
    docker)
		# create a subshell to run the docker command in its own environment
		(
        eval "$(docker-machine env $MACHINE)"

        shift
	  	rerun_log info "executing: docker $@"

        eval docker $*
    	)
		;;
	*)
		# Execute an adhoc command on the machine
		rerun_log info "executing: $DOCKER_COMMAND ssh $MACHINE $@"
		$DOCKER_COMMAND ssh $MACHINE "$COMMAND"
	;;
esac

# Done. Exit with last command exit status.
exit $?

